server:
  port: 8083
  servlet:
    context-path: /

# 产品制作
wordproduct:
  ## doc配置
  # ftl文件根路径
  ftlBasePath: "/data/product/template/docTemplate/"
  # 高温ftl文件名称
  highTmpDaysFtlFileName: "highTmpDays.ftl"
  # 气候监测ftl文件名称
  climateMonitorFtlName: "climateMonitor.ftl"
  # 生成的word文件存放根路径
  wordOutBasePath: "/data/product/productOut/"

  ## docx配置
  # 产品(doc,pdf)存放根路径
  productBasePath: "/data/product/productOut/"
  # 模板zip文件存放根路径
  zipFileBasePath: "/data/product/template/docxTemplate/"
  # 附件上传根路径
  accessoryFileBasePath: "/data/product/accessory/"

  # 气候监测zip文件存放子路径((document.ftl和document.xml.rels.ftl也放在此目录下))
  climateMonitorZipFileChildPath: "climiteMonitor/"
  # 气候监测模板zip文件名称字符串
  climateMonitorZipFileBaseName: "climiteMonitor"

  # 高温日数zip文件存放子路径
  highTmpZipFileChildPath: "highTempDays/"
  # 高温日数模板zip文件名称字符串
  highTmpZipFileBaseName: "highTempDays"

  # 月气候评价zip文件存放子路径
  monthClimateEvaluateZipFileChildPath: "monthClimateEvaluate/"
  # 月气候评价模板zip文件名称字符串
  monthClimateEvaluateZipFileBaseName: "monthClimateEvaluate"

  # 季气候评价zip文件存放子路径
  quarterClimateEvaluateZipFileChildPath: "quarterClimateEvaluate/"
  # 季气候评价模板zip文件名称字符串
  quarterClimateEvaluateZipFileBaseName: "quarterClimateEvaluate"

  # 暴雨过程zip文件存放子路径
  heavyRainProcessZipFileChildPath: "heavyRainProcess/"
  # 暴雨过程模板zip文件名称字符串
  heavyRainProcessZipFileBaseName: "heavyRainProcess"

  # 文件服务器ip,端口
  fileServer: "http://10.230.124.156:8109"