server:
  port: 8899
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated  #消息发送到交换机确认机制，是否确认回调
    publisher-returns: true   #  消息发送到交换机确认机制,是否确认回调（消息发送失败返回队列中）
    virtual-host: /    #连接到rabbitMQ的vhost
    listener:
      simple:
        acknowledge-mode: manual  #manual：采用手动应答；none：不确认；auto：自动确认
        prefetch: 1 #限制每次发送一条数据。
        concurrency: 1 #指定最小消费者数量
        max-concurrency: 1 #指定最大消费者数量
        retry:
          enabled: true #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          max-attempts: 5 #最大重试次数
          initial-interval: 1ms #重试间隔时间（单位毫秒）第一次和第二次尝试发布或传递消息之间的间隔
          max-interval: 1000ms #重试最大时间间隔（单位毫秒）
          multiplier: 5 #应用于上一重试间隔的乘数
logging:
  level:
    com:
      qjc:
        mq: debug